content:
  - name: articles
    label: 文章撰寫
    type: collection
    path: content
    subfolders: true

    exclude:
      - index.md

    format: yaml-frontmatter

    filename:
      template: "{year}-{month}-{day}-{hour}{minute}{second}.md"
      field: create

    view:
      layout: tree
      primary: title
      fields:
        - title
      search:
        - title
        - body

    fields:
      - name: title
        label: 文章標題
        type: string
        required: true

      - name: body
        label: 文章內容
        type: rich-text
        options:
          format: markdown
          switcher: true
          media: false