content:
  - name: articles
    label: 文章
    type: collection
    path: content
    subfolders: true

    exclude:
      - index.md

    format: yaml-frontmatter

    filename: "{primary}.md"

    view:
      layout: tree
      primary: title
      fields:
        - title
      search:
        - title
        - body

    fields:
      - name: title
        label: 標題
        type: string
        required: true

      - name: body
        label: 文章內容
        type: rich-text
        options:
          format: markdown
          switcher: true
          media: false